public enum NeighbourState {
    CHOKED,
    UNCHOKED,
    INTERESTED,
    NOT_INTERESTED,
    CHOKED_AND_INTERESTED,
    CHOKED_AND_NOT_INTERESTED,
    UNCHOKED_AND_INTERESTED,
    UNCHOKED_AND_NOT_INTERESTED,
    UNKNOWN

}
